[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
# Domain dependencies
uuid = { version = "1.21.0", features = ["v7", "serde"] }
time = "0.3.47"
hulu_core = { package = "core", path = "../core" }
# Application layer dependencies
async-trait = "0.1.89"
serde = { version = "1.0.228", features = ["derive"] }
argon2 = "0.6.0-rc.7"
password-hash = "0.6.0-rc.12"

# Infrastructure dependencies
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "macros", "uuid", "time", "chrono"] }
jsonwebtoken = { version = "10.3.0", default-features = false, features = ["rust_crypto"] }

# Error handling
anyhow = "1.0.102"
thiserror = "2.0.18"

# API documentation
utoipa = { version = "5.4.0", features = ["axum_extras", "uuid", "debug"] }
utoipa-axum = { version = "0.2.0" }

# HTTP framework (for API layer)
axum = { version = "0.8.8" }

sea-orm = { version = "2.0.0-rc.38" }
strum = "0.28.0"
strum_macros = "0.28.0"
