[package]
name = "presentation"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[[bin]]
name = "presentation"
path = "src/main.rs"

[dependencies]
leptos = { version = "0.7", features = ["csr", "ssr"] }
leptos_router = { version = "0.7" }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
http = "1"
axum = "0.8"
