[package]
name = "Rust"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/*",
    "migration"
]

resolver = "2"
[dependencies]
# Feature crates
auth = { path = "crates/auth" }
merchant = { path = "crates/merchant" }
payments = { path = "crates/payments" }
arifpay = { path = "crates/arifpay" }
hulu_core = { package = "core", path = "crates/core" }
tokio = { version = "1.49.0", features = ["full"] }
axum = { version = "0.8.8" }
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "macros"] }
anyhow = "1.0.102"
dotenvy = "0.15.7"
utoipa = { version = "5.4.0", features = ["axum_extras", "uuid"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
utoipa-axum = { version = "0.2.0" }
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt", "json"] }
tower-http = { version = "0.6", features = ["cors"] }
tracing = "0.1.44"
sea-orm = { version = "2.0.0-rc.38", features = ["sqlx-postgres", "runtime-tokio", "schema-sync", "debug-print", "with-chrono", "with-json", "with-uuid", "entity-registry"] }
serde = { version = "1.0.228", features = ["derive"] }
